#----------------------------------------------------------------------------------------
# Dev: Aaron Baumgarner
# Created: 
# Description: This script is used to query the computer for the pass interval. On a 
#				frozen machine, if the interval is not 0 the binding will drop off and
#				will need to be thawed and rebound.
#----------------------------------------------------------------------------------------
#!/bin/bash

# The cut command splits the string passed in based on the delimiter (-d). In order
# to print a specific part of the new string array generated by cut you have to specify
# the number of indexes to include with a range or a single number (-f #-# or -f #).

# This will query the computer for its AD information, look for a specific line that 
# contains the phrase sent into grep, trim the result down to only the information 
# you want to be displayed with cut. Finally the string is stored in a local variable.
result=`dsconfigad -show | grep Password* | cut -d = -f 2`

# This will print the string created and stored in the variable result to the screen.
echo "<result>$result</result>"

# Exits the script safely.
exit 0